### ISSUE TITLE
alpine-caddy:php can not up

### ISSUE THREAD

**Issue by Tiebob** [yobasystems/alpine-caddy#3]
Hello, Dominic
I am bob. I pulled your docker image 'alpine-caddy' and ran as daemon. It ran up ok.
But I ran 'alpine-caddy:php', It failed to run and logs is the following: 
> no action found for directive 'startup' with server type 'http' (missing a plugin?)

**Comment by dominictayloruk** [comment]
Should be sorted now.

```
$ docker run yobasystems/alpine-caddy:php                                                                                                                                                dominictaylor@imac-27
Activating privacy features... done.

Serving HTTP on port 2015 
http://0.0.0.0:2015
```
