### ISSUE TITLE
Link to Yoba Systems in README is broken

### ISSUE THREAD

**Issue by dzek69** [yobasystems/alpine-caddy#4]
Maybe it's not the best place to report, as it doesn't much relate to alpine-caddy, but 🤷🏻‍♂️ 

On the bottom of README there is a link do Yoba Systems webpage, on .co.uk, which redirects to another domain yoba.systems which complains about some invalid SSL certificate.

**Comment by dominictayloruk** [comment]
Nothing to worry about
