### ISSUE TITLE
Cannot start PHP version

### ISSUE THREAD

**Issue by CyrosX** [yobasystems/alpine-caddy#5]
I'm getting this error from docker, while setting it up with this command:
docker run -d --name spooler -v $(pwd):/srv -p 2015:2015 yobasystems/alpine-caddy:php

```
run: reading config file: open /etc/caddy/Caddyfile: no such file or directory

```

**Comment by Tiebob** [comment]
> 
change the Caddyfile at container's path
docker run -d --name spooler -v $(pwd):/srv -p 2015:2015 -v _**your-caddyfile-path**_:/etc/caddy/Caddyfile yobasystems/alpine-caddy:php
